//  Assemble
//  Created by David Spry on 18/5/20.
//  Copyright © 2020 David Spry. All rights reserved.

import Foundation

/// A factory preset and its full state

struct EmptyPreset
{
    static var preset: AUAudioUnitPreset {
        let preset = AUAudioUnitPreset()
        preset.name = "Init"
        preset.number = 1
        return preset
    }
    
    static let state: [String : Any]? =
    [
        "name": "Init",
        "type": 1635084142,
        "version": 1,
        "subtype": 1095978306,
        "preset-number": 1,
        "manufacturer": 1146310738,
        "P0" : "1",
        "P1" : "0",
        "P2" : "0",
        "P3" : "0",
        "P4" : "0",
        "P5" : "0",
        "P6" : "0",
        "P7" : "0",
        "data": Data(base64Encoded: "AQAAAA8AAABwAGEAcgBhAG0AZQB0AGUAcgBzAEMAbABvAGMAawAAAAkAAABrAEMAbABvAGMAawBCAFAATQAAAPBCAAARAAAAawBDAGwAbwBjAGsAUwB1AGIAZABpAHYAaQBzAGkAbwBuAAAAgED/AQ4AAABwAGEAcgBhAG0AZQB0AGUAcgBzAFMAaQBuAGUAAAAAAA0AAABrAFMAaQBuAEEAbQBwAEEAdAB0AGEAYwBrAAAAoEAAAAsAAABrAFMAaQBuAEEAbQBwAEgAbwBsAGQAAAAAAAAADgAAAGsAUwBpAG4AQQBtAHAAUgBlAGwAZQBhAHMAZQAAAPpDAAAAABAAAABrAFMAaQBuAEYAaQBsAHQAZQByAEEAdAB0AGEAYwBrAAAAoEAAAAAADgAAAGsAUwBpAG4ARgBpAGwAdABlAHIASABvAGwAZAAAAAAAAAAAABEAAABrAFMAaQBuAEYAaQBsAHQAZQByAFIAZQBsAGUAYQBzAGUAAAB6Q/8BEAAAAHAAYQByAGEAbQBlAHQAZQByAHMAUwBxAHUAYQByAGUAAAAAAA0AAABrAFMAcQByAEEAbQBwAEEAdAB0AGEAYwBrAAAAoEAAAAsAAABrAFMAcQByAEEAbQBwAEgAbwBsAGQAAAAAAAAADgAAAGsAUwBxAHIAQQBtAHAAUgBlAGwAZQBhAHMAZQAAAPpDAAAAABAAAABrAFMAcQByAEYAaQBsAHQAZQByAEEAdAB0AGEAYwBrAAAAcEEAAAAADgAAAGsAUwBxAHIARgBpAGwAdABlAHIASABvAGwAZAAAAAAAAAAAABEAAABrAFMAcQByAEYAaQBsAHQAZQByAFIAZQBsAGUAYQBzAGUAAAB6Q/8BEgAAAHAAYQByAGEAbQBlAHQAZQByAHMAVAByAGkAYQBuAGcAbABlAAAAAAANAAAAawBUAHIAaQBBAG0AcABBAHQAdABhAGMAawAAAKBAAAALAAAAawBUAHIAaQBBAG0AcABIAG8AbABkAAAAAAAAAA4AAABrAFQAcgBpAEEAbQBwAFIAZQBsAGUAYQBzAGUAAAD6QwAAAAAQAAAAawBUAHIAaQBGAGkAbAB0AGUAcgBBAHQAdABhAGMAawAAAHBBAAAAAA4AAABrAFQAcgBpAEYAaQBsAHQAZQByAEgAbwBsAGQAAAAAAAAAAAARAAAAawBUAHIAaQBGAGkAbAB0AGUAcgBSAGUAbABlAGEAcwBlAAAAekP/ARIAAABwAGEAcgBhAG0AZQB0AGUAcgBzAFMAYQB3AHQAbwBvAHQAaAAAAAAADQAAAGsAUwBhAHcAQQBtAHAAQQB0AHQAYQBjAGsAAACgQAAACwAAAGsAUwBhAHcAQQBtAHAASABvAGwAZAAAAAAAAAAOAAAAawBTAGEAdwBBAG0AcABSAGUAbABlAGEAcwBlAAAA+kMAAAAAEAAAAGsAUwBhAHcARgBpAGwAdABlAHIAQQB0AHQAYQBjAGsAAABwQQAAAAAOAAAAawBTAGEAdwBGAGkAbAB0AGUAcgBIAG8AbABkAAAAAAAAAAAAEQAAAGsAUwBhAHcARgBpAGwAdABlAHIAUgBlAGwAZQBhAHMAZQAAAHVD/wEQAAAAcABhAHIAYQBtAGUAdABlAHIAcwBGAGkAbAB0AGUAcgAAAAAAEwAAAGsAUwBpAG4ARgBpAGwAdABlAHIARgByAGUAcQB1AGUAbgBjAHkAAACAPwAAEwAAAGsAUwBpAG4ARgBpAGwAdABlAHIAUgBlAHMAbwBuAGEAbgBjAGUAbxKDOgAAEwAAAGsAVAByAGkARgBpAGwAdABlAHIARgByAGUAcQB1AGUAbgBjAHkAAACAPwAAEwAAAGsAVAByAGkARgBpAGwAdABlAHIAUgBlAHMAbwBuAGEAbgBjAGUAbxKDOgAAEwAAAGsAUwBxAHIARgBpAGwAdABlAHIARgByAGUAcQB1AGUAbgBjAHkAMzNzPwAAEwAAAGsAUwBxAHIARgBpAGwAdABlAHIAUgBlAHMAbwBuAGEAbgBjAGUAbxKDOgAAEwAAAGsAUwBhAHcARgBpAGwAdABlAHIARgByAGUAcQB1AGUAbgBjAHkAAACAPwAAEwAAAGsAUwBhAHcARgBpAGwAdABlAHIAUgBlAHMAbwBuAGEAbgBjAGUAbxKDOv8BFQAAAHAAYQByAGEAbQBlAHQAZQByAHMAUwB0AGUAcgBlAG8ARABlAGwAYQB5AAAADAAAAGsARABlAGwAYQB5AFQAbwBnAGcAbABlAAAAgD8AAAAADgAAAGsARABlAGwAYQB5AEYAZQBlAGQAYgBhAGMAawDMzMw9AAAAABEAAABrAFMAdABlAHIAZQBvAEQAZQBsAGEAeQBMAFQAaQBtAGUAAAAAQQAAEQAAAGsAUwB0AGUAcgBlAG8ARABlAGwAYQB5AFIAVABpAG0AZQAAAABBAAAJAAAAawBEAGUAbABhAHkATQBpAHgAAACAPgAAEgAAAGsAUwB0AGUAcgBlAG8ARABlAGwAYQB5AE8AZgBmAHMAZQB0AAAAQED/AQAAEQAAAHAAYQByAGEAbQBlAHQAZQByAHMAVgBpAGIAcgBhAHQAbwAAAA4AAABrAFYAaQBiAHIAYQB0AG8AVABvAGcAZwBsAGUAAACAPwAAAAANAAAAawBWAGkAYgByAGEAdABvAFMAcABlAGUAZAAAAEBAAAANAAAAawBWAGkAYgByAGEAdABvAEQAZQBwAHQAaADMzMw9//8=") ?? Data()
    ]

}
